### ISSUE TITLE
What's the difference between this driver and HoneywellThermo-TCC?

### ISSUE THREAD

**Issue by heatvent** [HubitatCommunity/HoneywellThermoParent#1]
This looks like it was created after HoneywellThermo-TCC so assuming this is more current?  Can you confirm which to use?

Thanks!

**Comment by csteele-PD** [comment]
This Parent/Child driver is the latest and where development is focused. It's targeting homes with more than one Thermostat. Honeywell limits access and multiple thermostats can overuse their API. This Parent/child will accumulate commands into one Honeywell session. 

There's no functional difference between the two for homes with a single Thermostat (such as my own.) I have back-ported all the good ideas from this driver to the older one, but that isn't a promise.
